--can't run on dedicated because no support for the string_agg ordinal

declare @ALGO VARCHAR(8) = 'SHA2_256'
	declare	@SCHEMA NVARCHAR(128)='enriched'
	declare	@TABLE NVARCHAR(128)='CheckImagingStatesLK'
	declare	@EXCLUDE NVARCHAR(MAX)='Id' --'CheckImagingStatesId'

	DECLARE @LIST NVARCHAR(MAX) = ''
	DECLARE @OUTPUT NVARCHAR(MAX) = ''
	DECLARE @TARGET NVARCHAR(128) = CONCAT(@SCHEMA,',',@TABLE)


	SELECT @OUTPUT = CONCAT('HASHBYTES(''',@ALGO,''',(CONCAT(COALESCE(CAST(',STRING_AGG(QUOTENAME(COLUMN_NAME), ' AS NVARCHAR(MAX)),''^''),''|'',COALESCE(CAST(') WITHIN GROUP (ORDER BY ORDINAL_POSITION),' AS NVARCHAR(MAX)),''^''))))')
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = @TABLE
	AND COLUMN_NAME NOT IN (SELECT value FROM STRING_SPLIT(@EXCLUDE,',') )

	select @OUTPUT


select	HASHBYTES('SHA2_256',CONCAT(
								COALESCE(CAST('-1' AS NVARCHAR(MAX)),'^')
								,'|' ,COALESCE('Unknown','^') ) )